WebAppMVC/Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppMVC.Models;

[Table("category")]
public class Category
{
    [Key]
    [Column("id")]
    public int Id { get; set; }
    [Column("name")]
    public string Name { get; set; }
    [Column("display_order")]
    public int DisplayOrder { get; set; }
}

WebAppMVC/Models/ErrorViewModel.cs
namespace WebAppMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebAppMVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Data;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers;

public class CategoryController : Controller
{
    // GET

    private readonly ApplicationDbContext _db;

    public CategoryController(ApplicationDbContext db)
    {
        _db = db;
    }
    
    public IActionResult Index()
    {

        IEnumerable<Category> objList = _db.Category;
        return View(objList);
    }
}

WebAppMVC/Controllers/DapperTestController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Data;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers
{
    public class DapperTestController : Controller
    {
        ICategoryRepository repo;
        public DapperTestController(ICategoryRepository r)
        {
            repo = r;
        }
        public ActionResult Index()
        {
            return View(repo.GetCategories());
        }
 
        public ActionResult Details(int id)
        {
            Category category = repo.Get(id);
            if (category != null)
                return View(category);
            return NotFound();
        }
 
        public ActionResult Create()
        {
            return View();
        }
 
        [HttpPost]
        public ActionResult Create(Category category)
        {
            repo.Create(category);
            return RedirectToAction("Index");
        }
 
        public ActionResult Edit(int id)
        {
            Category category = repo.Get(id);
            if (category != null)
                return View(category);
            return NotFound();
        }
 
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            repo.Update(category);
            return RedirectToAction("Index");
        }
 
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            Category category = repo.Get(id);
            if (category != null)
                return View(category);
            return NotFound();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WebAppMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

WebAppMVC/Views/Category/Index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model IEnumerable<WebAppMVC.Models.Category>
@{
    ViewData["Title"] = "Index";
    
}

<div class="container p-3">
    
    <div class="row pt4">
        <div class="col-6">
            
            <h2 class="text-primary">Category list Entity Framework</h2>
            
        </div>
        <div class="col-6">
            Create new category
        </div>
        <br/>
        <br/>
        @if (Model.Count() > 0)
        {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
            <tr>
                <th>Category name</th>
                <th>Display order</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td style="width:50%">@obj.Name</td>
                    <td style="width:30%">@obj.DisplayOrder</td>
                    <td>Add/Remove</td>
                </tr>
            }
            </tbody>
        </table>                    
        }
        else
        {
            <p>No category in DB</p>    
        }
        
        
    </div>
    
    
</div>



@* TODO list categories from db *@

WebAppMVC/Views/DapperTest/Create.cshtml
@model WebAppMVC.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayOrder" class="control-label"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebAppMVC/Views/DapperTest/Delete.cshtml
@model WebAppMVC.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebAppMVC/Views/DapperTest/Details.cshtml
@model WebAppMVC.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebAppMVC/Views/DapperTest/Edit.cshtml
@model WebAppMVC.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayOrder" class="control-label"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebAppMVC/Views/DapperTest/Index.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model IEnumerable<Category>
@{
    ViewData["Title"] = "Index";
    
}

<div class="container p-3">
    
    <div class="row pt4">
        <div class="col-6">
            
            <h2 class="text-primary">Category list via <b>Dapper</b></h2>
            
        </div>
        <div class="col-6">
            Create new category
        </div>
        <br/>
        <br/>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                <tr>
                    <th>Category name</th>
                    <th>Display order</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td style="width:50%">@obj.Name</td>
                        <td style="width:30%">@obj.DisplayOrder</td>
                        <td>Add/Remove</td>
                    </tr>
                }
                </tbody>
            </table>                    
        }
        else
        {
            <p>No category in DB</p>    
        }
        
        
    </div>
    
    
</div>

WebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
    <a class="nav-link text-green" asp-area="" asp-controller="DapperTest" asp-action="Index">
        list all Categories with Dapper
    </a>
    <p>CRUD Api: /DapperTest/Details/:id</p>
   
    
</div>

WebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebAppMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">list_EF</a>
                    </li>
                      <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="DapperTest" asp-action="Index">list_Dapper</a>
                                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - WebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>